from typing import Any, Optional, Union
from stitcher.needle import SemanticPointer, needle
from .protocols import Renderer

bus: Any

class MessageBus:
    def __init__(self): ...

    def set_renderer(self, renderer: Renderer): ...

    def _render(self, level: str, msg_id: Union[str, SemanticPointer], **kwargs: Any) -> None: ...

    def info(self, msg_id: Union[str, SemanticPointer], **kwargs: Any) -> None: ...

    def success(self, msg_id: Union[str, SemanticPointer], **kwargs: Any) -> None: ...

    def warning(self, msg_id: Union[str, SemanticPointer], **kwargs: Any) -> None: ...

    def error(self, msg_id: Union[str, SemanticPointer], **kwargs: Any) -> None: ...

    def render_to_string(self, msg_id: Union[str, SemanticPointer], **kwargs: Any) -> str:
        """Resolves a message to a string without sending it to the renderer."""
        ...