from pathlib import Path
from stitcher.io import YamlAdapter

def test_yaml_adapter_load_non_existent(tmp_path: Path): ...

def test_yaml_adapter_round_trip(tmp_path: Path): ...

def test_yaml_adapter_handles_malformed(tmp_path: Path): ...

def test_yaml_adapter_multiline_format(tmp_path: Path):
    """Verify that multiline strings are saved using Literal Block Style (|)."""
    ...