import libcst as cst
from typing import Dict, List, Optional, Union

HasBody: Any

def strip_docstrings(source_code: str) -> str:
    """Removes all docstrings from the source code."""
    ...

def inject_docstrings(source_code: str, docs: Dict[str, str]) -> str:
    """Injects docstrings from the dictionary into the source code."""
    ...

class StripperTransformer(cst.CSTTransformer):
    def _is_docstring(self, node: cst.BaseSmallStatement) -> bool:
        """Check if a statement is a standalone string expression (docstring)."""
        ...

    def _process_body(self, body: Union[cst.BaseSuite, cst.SimpleStatementSuite]) -> Union[cst.BaseSuite, cst.SimpleStatementSuite]:
        """Removes docstring from body. If body becomes empty, inserts 'pass'."""
        ...

    def leave_Module(self, original_node: cst.Module, updated_node: cst.Module) -> cst.Module: ...

    def leave_FunctionDef(self, original_node: cst.FunctionDef, updated_node: cst.FunctionDef) -> cst.FunctionDef: ...

    def leave_ClassDef(self, original_node: cst.ClassDef, updated_node: cst.ClassDef) -> cst.ClassDef: ...

class InjectorTransformer(cst.CSTTransformer):
    def __init__(self, docs: Dict[str, str]): ...

    def _get_current_fqn(self, name: str) -> str: ...

    def _create_docstring_node(self, doc_content: str) -> cst.SimpleStatementLine:
        """Creates a properly quoted docstring node."""
        ...

    def _is_docstring(self, node: cst.BaseSmallStatement) -> bool: ...

    def _inject_into_body(self, body: Union[cst.BaseSuite, cst.SimpleStatementSuite], doc_content: str) -> Union[cst.BaseSuite, cst.SimpleStatementSuite]: ...

    def visit_ClassDef(self, node: cst.ClassDef) -> Optional[bool]: ...

    def leave_ClassDef(self, original_node: cst.ClassDef, updated_node: cst.ClassDef) -> cst.ClassDef: ...

    def visit_FunctionDef(self, node: cst.FunctionDef) -> Optional[bool]: ...

    def leave_FunctionDef(self, original_node: cst.FunctionDef, updated_node: cst.FunctionDef) -> cst.FunctionDef: ...

    def leave_Module(self, original_node: cst.Module, updated_node: cst.Module) -> cst.Module: ...