from typing import Protocol, Dict, Union, Optional, Any
from pathlib import Path

from .docstring import DocstringIR
from .fingerprint import Fingerprint
from .models import ModuleDef


class DocumentManagerProtocol(Protocol):
    def load_docs_for_module(self, module: ModuleDef) -> Dict[str, DocstringIR]: ...

    def load_docs_for_path(self, file_path: str) -> Dict[str, DocstringIR]: ...

    def save_docs_for_module(self, module: ModuleDef) -> Path: ...

    def flatten_module_docs(self, module: ModuleDef) -> Dict[str, DocstringIR]: ...

    def compute_yaml_content_hashes(self, module: ModuleDef) -> Dict[str, str]: ...

    def compute_yaml_content_hash(self, content: Union[str, Dict[str, Any]]) -> str: ...

    def hydrate_module(
        self,
        module: ModuleDef,
        force: bool = False,
        reconcile: bool = False,
        resolution_map: Optional[Dict[str, Any]] = None,
        dry_run: bool = False,
        source_docs_override: Optional[Dict[str, DocstringIR]] = None,
    ) -> Dict[str, Any]: ...

    def reformat_docs_for_module(self, module: ModuleDef) -> bool: ...

    def serialize_ir(self, ir: DocstringIR) -> Union[str, Dict[str, Any]]: ...

    def compute_ir_hash(self, ir: DocstringIR) -> str: ...

    def dump_data(self, data: Dict[str, Any]) -> str: ...

    def load_raw_data(self, file_path: str) -> Dict[str, Any]: ...

    def dump_raw_data_to_string(self, data: Dict[str, Any]) -> str: ...


class SignatureManagerProtocol(Protocol):
    def load_composite_hashes(self, file_path: str) -> Dict[str, Fingerprint]: ...

    def save_composite_hashes(
        self, file_path: str, hashes: Dict[str, Fingerprint]
    ) -> None: ...

    def reformat_hashes_for_file(self, file_path: str) -> bool: ...

    # Used by PumpRunner for centralized serialization
    def serialize_hashes(
        self, file_path: str, hashes: Dict[str, Fingerprint]
    ) -> str: ...

    def get_signature_path(self, file_path: str) -> Path: ...
