from stitcher.needle import L, SemanticPointer

def test_root_pointer_is_empty(): ...

def test_attribute_access_builds_path(): ...

def test_deep_nesting(): ...

def test_equality_with_string(): ...

def test_equality_with_pointer(): ...

def test_representation(): ...

def test_hashability(): ...