from textwrap import dedent
from stitcher.scanner.transformer import strip_docstrings, inject_docstrings

def test_strip_docstrings_basic(): ...

def test_strip_docstrings_replaces_with_pass():
    """If a function only has a docstring, stripping it should leave a pass."""
    ...

def test_strip_class_and_module_docs(): ...

def test_inject_docstrings_basic(): ...

def test_inject_docstrings_replacement(): ...

def test_inject_nested_fqn(): ...

def test_inject_multiline_handling(): ...